### ISSUE TITLE
Error 500 when using latest released tag

### ISSUE THREAD

**Issue by Christian-Schou** [tschannik/caprover-umami#6]
Hi

I am trying to deploy this on my Caprover instance, but I get the following error when I use the latest tag for version 1.20.0

In the field: Caprover Umami Version I tested both 1.20.0 and postgresql-ae7186c but it returns error 500 when it reaches the last step in the Caprover deployment.

When using the standard pre-filled tag it deploys without any issues?

**Comment by Christian-Schou** [comment]
Is this project not active anymore?

**Comment by tschannik** [comment]
Sorry i was on vacation. Will have a look into it next week

**Comment by adryserage** [comment]
@Christian-Schou pull request sent for update !

Check : #7 and #8
